/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sustav;

import com.sustav.springinaction.Knight;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("knight.xml");
        Knight knight = context.getBean("knight", Knight.class);
        knight.embarkOnQuest();

    }
}
